### ISSUE TITLE
480 MHz, life expectancy

### ISSUE THREAD

**Issue by serjepatoff** [davidb990/rp2040_xoc#2]
Great experiment, thank you. Of course 1 GHz is absolutely useless thing besides setting record high mark, but it raises one interesting question. 

How do you estimate the chance to run RPi Pico sustainably @ substantially more modest 480 MHz frequency? 

PS. Why 480? To match USB2 HS baud rate, then try to implement PIO-driven HS.

**Comment by davidb990** [comment]
Hiya,

I think you could run an RP2040 at 480 MHz fairly sustainably, but with a few caveats.

A fast RP2040 chip will run at around 420 MHz at 1.3V on the DVDD (the maximum voltage allowed by VSEL,), so one would still need to provide an external voltage (I'd guess around 1.5V) to the cores on the DVDD pins. As described in this repo, the flash can't keep up above ~270MHz, so all programs will need to run from SRAM, and for USB you'd probably want a more stable clock than the ROSC, so using the XOSC would give you your best chance of implementing PIO-driven HS.

With all that being said, I don't know for certain how long the RP2040 would last at ~1.5V; I suspect it would be able to take it, but there's a good chance you'll end up with a dead chip before too long!

Good luck, and let me know how you get on!
